CREATE TABLE IF NOT EXISTS RULES (
    RULE_NAME CHARACTER VARYING(255),
    PRODUCT_TYPE CHARACTER VARYING(255),
    TRANSACTION_TYPE CHARACTER VARYING(255),
    AMOUNT INTEGER,
    CONDITION CHARACTER VARYING(2),
    ANNOTATION CHARACTER VARYING(255)
);