CREATE TABLE IF NOT EXISTS RULE (
    id TEXT,
    INSTRUCTION TEXT,
    ANNOTATION TEXT
);

CREATE TABLE IF NOT EXISTS RECOMMENDATION_RULES (
    RECOMMENDATION_ID TEXT,
    RULE_ID TEXT
);

CREATE TABLE IF NOT EXISTS RECOMMENDATION (
    ID TEXT,
    NAME TEXT,
    ANNOTATION TEXT
);
