CREATE TABLE IF NOT EXISTS RULES (
    NAME TEXT,
    PRODUCT_TYPE TEXT,
    TRANSACTION_TYPE TEXT,
    AMOUNT INTEGER,
    CONDITION CHARACTER VARYING(2),
    ANNOTATION TEXT
);

CREATE TABLE IF NOT EXISTS RECOMMENDATION_RULES (
    ID TEXT,
    PART INTEGER,
    RULE_NAME TEXT
);

CREATE TABLE IF NOT EXISTS RECOMMENDATION (
    ID TEXT,
    NAME TEXT,
    ANNOTATION TEXT
);
