CREATE TABLE IF NOT EXISTS RULE(
QUERY TEXT UNIQUE NOT NULL,
ARGUMENT01 TEXT,
ARGUMENT02 TEXT,
ARGUMENT03 TEXT,
ARGUMENT04 TEXT
NEGATIVE BOOLEAN
);

CREATE TABLE IF NOT EXISTS RECOMMENDATION(
ID TEXT,
NAME TEXT,
TEXT TEXT,
RULE TEXT
);