springdoc.packages-to-scan=star,star.controller
springdoc.paths-to-match=/recommendation/**,/example/**

application.transactions-db.url=jdbc:h2:file:./transaction
application.rules.url=jdbc:h2:file:./recommendations
spring.sql.init.schema-locations=classpath:schema-init.sql


application.rules.username=sa
application.rules.password=
application.rules.driver-class-name=org.h2.Driver